Repository mozilla-services/telescope, pull requests merged in 2024-09, with the labels that each got.

#1480 Fixing dependabot PR check
  .github/workflows/dependabot-automerge.yaml
Labels: github_actions

#1485 Remove deprecation warnings
  checks/core/certificate_expiration.py
  checks/remotesettings/certificates_expiration.py
  pyproject.toml
  telescope/app.py
  telescope/utils.py
  tests/checks/core/test_certificate_expiration.py
  tests/checks/remotesettings/test_certificates_expiration.py
  tests/test_basic_endpoints.py
  tests/test_utils.py
Labels: dependencies

#1486 Add 'period_sampling_seconds' param instead of hard-coded 600 seconds
  checks/normandy/jexl_error_rate.py
  checks/normandy/reported_recipes.py
  checks/normandy/uptake_error_rate.py
  checks/remotesettings/uptake_error_rate.py
  checks/remotesettings/uptake_max_age.py
  tests/checks/remotesettings/test_uptake_error_rate.py
Labels: enhancement

#1487 Fix #1484: keep only one status per client per source and per period
  checks/remotesettings/uptake_error_rate.py
Labels: bug

#1488 Drop taskcluster checks
  Dockerfile
  Makefile
  bin/run.sh
  checks/taskcluster/__init__.py
  checks/taskcluster/create_task.py
  checks/taskcluster/latest_indexed.py
  checks/taskcluster/utils.py
  checks/taskcluster/write_secrets.py
  poetry.lock
  pyproject.toml
  tests/checks/taskcluster/test_create_task.py
  tests/checks/taskcluster/test_latest_indexed.py
  tests/checks/taskcluster/test_write_secrets.py
Labels: enhancement

#1473 Fix #1472: check attachments bundle
  checks/remotesettings/attachments_bundles.py
  telescope/utils.py
  tests/checks/remotesettings/test_attachments_bundles.py
Labels: enhancement
